### PR TITLE
Group feature

### PR DESCRIPTION
**Pull request by Excel1**
With this change it is now possible to add the user to certain groups via a mapper (ownCloudGroups) or a variable.

### CODE REVIEW

**Comment by Excel1** [comment]
If it is possible to get all groups of a user from Nextcloud then we could compare the groups from NC with the groups from the claim and remove users from groups

**Comment by Excel1** [comment]
I didnt moved the string ownCloudGroups to the oidc_login_attributes setting because i dont know how to use it right and i dont know which default value we wanna apply

**Comment by pulsejet** [comment]
Sorry for the delay, been caught up in a catastrophic hardware failure mess. I'll try to fix this up, test and merge over the next few days.

**Comment by pulsejet** [comment]
Merged, thanks!

**Pull request merged**
