### PR TITLE
Declare NC 23 compatibility

### PR DESCRIPTION
**Pull request by danimo**
Addresses #146 when released as new version.

### CODE REVIEW

**Comment by azmeuk** [comment]
Thank you!

**Comment by Ornias1993** [comment]
@azmeuk Thanks for merging.
Would you mind triggering another release for this, so Nextcloud actually accepts it as well?
Considering there are no other precise reports of issues and multiple reports of "no-issues" on Nextcloud 23, that seems acceptable.

**Comment by pulsejet** [comment]
@Ornias1993 @azmeuk just pushed a release to the store for master

**Comment by Ornias1993** [comment]
Thanks @pulsejet  :)

**Pull request merged**
